theme: academic-jekyll-theme

url: "https://loicgrobol.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

name: LoÃ¯c Grobol
emojicon: "ðŸŒ³"
first_name: LoÃ¯c
last_name: Grobol

plugins:
  - jekyll-redirect-from

header: "assets/img/2022-05-26-howth_hidden_beach_banner.jpg"

include: ["_pages"]
exclude: ["README.md"]